mod based_on;
mod color;
mod doc_defaults;
mod justification;
mod name;
mod next;
mod paragraph;
mod paragraph_property;
mod q_format;
mod run;
mod run_property;
mod run_property_default;
mod style;
mod sz;
mod text;

pub use based_on::*;
pub use color::*;
pub use doc_defaults::*;
pub use justification::*;
pub use name::*;
pub use next::*;
pub use paragraph::*;
pub use paragraph_property::*;
pub use q_format::*;
pub use run::*;
pub use run_property::*;
pub use run_property_default::*;
pub use style::*;
pub use sz::*;
pub use text::*;
