// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlignmentType = "both" | "center" | "distribute" | "start" | "end" | "left" | "right" | "justified";