// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakType } from "./BreakType";

export interface Break { break_type: BreakType, }