// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteChild } from "./DeleteChild";

export interface Delete { author: string, date: string, children: Array<DeleteChild>, }