// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PicAlign } from "./PicAlign";

export type DrawingPosition = { offset: number } | { align: PicAlign };