// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FrameProperty { h?: number, hRule?: string, hAnchor?: string, hSpace?: number, vAnchor?: string, vSpace?: number, w?: number, wrap?: string, x?: number, xAlign?: string, y?: number, yAlign?: string, }