// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrameProperty = { 
/**
 * Frame Height
 * Represents the following attribute in the schema: w:h
 */
h: number | null, 
/**
 * Frame Height Type
 * Represents the following attribute in the schema: w:hRule
 */
hRule: string | null, 
/**
 * Frame Horizontal Positioning Base
 * Represents the following attribute in the schema: w:hAnchor
 */
hAnchor: string | null, 
/**
 * Horizontal Frame Padding
 * Represents the following attribute in the schema: w:hSpace
 */
hSpace: number | null, vAnchor: string | null, vSpace: number | null, w: number | null, 
/**
 * Text Wrapping Around Frame
 * Represents the following attribute in the schema: w:wrap
 */
wrap: string | null, 
/**
 * Absolute Horizontal Position
 * Represents the following attribute in the schema: w:x
 */
x: number | null, 
/**
 * Relative Horizontal Position
 * Represents the following attribute in the schema: w:xAlign
 */
xAlign: string | null, 
/**
 * Absolute Vertical Position
 * Represents the following attribute in the schema: w:y
 */
y: number | null, 
/**
 * Relative Vertical Position
 * Represents the following attribute in the schema: w:yAlign
 */
yAlign: string | null, };
