// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentRangeEnd } from "./CommentRangeEnd";
import type { CommentRangeStart } from "./CommentRangeStart";
import type { Delete } from "./Delete";
import type { Run } from "./Run";

export type InsertChild = { "Run": Run } | { "Delete": Delete } | { "CommentStart": CommentRangeStart } | { "CommentEnd": CommentRangeEnd };