// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstrHyperlink } from "./InstrHyperlink";
import type { InstrPAGEREF } from "./InstrPAGEREF";
import type { InstrTC } from "./InstrTC";
import type { InstrToC } from "./InstrToC";

export type InstrText = { "TOC": InstrToC } | { "TC": InstrTC } | { "PAGEREF": InstrPAGEREF } | { "HYPERLINK": InstrHyperlink } | { "Unsupported": string };