// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface InstrTC { text: string, omitsPageNumber: boolean, level: number | null, itemTypeIdentifier: string | null, }