// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionalTabAlignmentType } from "./PositionalTabAlignmentType";
import type { PositionalTabRelativeTo } from "./PositionalTabRelativeTo";
import type { TabLeaderType } from "./TabLeaderType";

export interface PositionalTab { alignment: PositionalTabAlignmentType, relativeTo: PositionalTabRelativeTo, leader: TabLeaderType, }