// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelativeFromHType = "character" | "column" | "insidemargin" | "leftmargin" | "margin" | "outsizemargin" | "page" | "rightmargin";