// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RunFonts { ascii?: string, hiAnsi?: string, eastAsia?: string, cs?: string, asciiTheme?: string, hiAnsiTheme?: string, eastAsiaTheme?: string, csTheme?: string, hint?: string, }