// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bold } from "./Bold";
import type { BoldCs } from "./BoldCs";
import type { Caps } from "./Caps";
import type { CharacterSpacing } from "./CharacterSpacing";
import type { Color } from "./Color";
import type { Delete } from "./Delete";
import type { Highlight } from "./Highlight";
import type { Insert } from "./Insert";
import type { Italic } from "./Italic";
import type { ItalicCs } from "./ItalicCs";
import type { RunFonts } from "./RunFonts";
import type { RunStyle } from "./RunStyle";
import type { SpecVanish } from "./SpecVanish";
import type { Strike } from "./Strike";
import type { Sz } from "./Sz";
import type { SzCs } from "./SzCs";
import type { TextBorder } from "./TextBorder";
import type { Underline } from "./Underline";
import type { Vanish } from "./Vanish";
import type { VertAlign } from "./VertAlign";

export interface RunProperty { style?: RunStyle, sz?: Sz, szCs?: SzCs, color?: Color, highlight?: Highlight, vertAlign?: VertAlign, underline?: Underline, bold?: Bold, boldCs?: BoldCs, caps?: Caps, italic?: Italic, italicCs?: ItalicCs, vanish?: Vanish, specVanish?: SpecVanish, characterSpacing?: CharacterSpacing, fonts?: RunFonts, textBorder?: TextBorder, del?: Delete, ins?: Insert, strike?: Strike, }