// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageData } from "./ImageData";

export interface Shape { style?: string, imageData?: ImageData, }