// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabLeaderType } from "./TabLeaderType";
import type { TabValueType } from "./TabValueType";

export interface Tab { val: TabValueType | null, leader: TabLeaderType | null, pos: number | null, }