// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableCellBorder } from "./TableCellBorder";

export interface TableCellBorders { top: TableCellBorder | null, left: TableCellBorder | null, bottom: TableCellBorder | null, right: TableCellBorder | null, insideH: TableCellBorder | null, insideV: TableCellBorder | null, tr2Bl: TableCellBorder | null, tl2Br: TableCellBorder | null, }