// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableCellBorder } from "./TableCellBorder";

export type TableCellBorders = { top: TableCellBorder | null, left: TableCellBorder | null, bottom: TableCellBorder | null, right: TableCellBorder | null, insideH: TableCellBorder | null, insideV: TableCellBorder | null, tr2bl: TableCellBorder | null, tl2br: TableCellBorder | null, };
