// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderType } from "./BorderType";
import type { TableCellBorderPosition } from "./TableCellBorderPosition";

export type TableCellBorder = { borderType: BorderType, size: number, color: string, position: TableCellBorderPosition, space: number, };
