// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.tablepositionproperties?view=openxml-3.0.1
 */
export type TablePositionProperty = { leftFromText: number | null, rightFromText: number | null, verticalAnchor: string | null, horizontalAnchor: string | null, positionXAlignment: string | null, positionYAlignment: string | null, positionX: number | null, positionY: number | null, };
