// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderType } from "./BorderType";

export interface TextBorder { borderType: BorderType, size: number, color: string, space: number, }